# Generated by Django 4.0.2 on 2022-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0004_remove_group_estudiantes_group_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group', max_length=50, verbose_name='Group Name'),
        ),
    ]
